apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: procar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: registry.pc-dev.nikichxp.xyz/procar/user:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_HOST
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_DATABASE
            - name: MONGO_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_APP_NAME
            - name: MONGODB_URI
              value: "mongodb+srv://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST)/$(MONGO_DATABASE)?appName=$(MONGO_APP_NAME)"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: procar
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 8084
      targetPort: 8084
