apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-provider-procar
  namespace: procar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-provider-procar
  template:
    metadata:
      labels:
        app: auction-provider-procar
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: auction-provider-procar
          image: registry.pc-dev.nikichxp.xyz/procar/auction-provider-procar:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_URI
              value: "redis://:$(REDIS_PASSWORD)@redis:6379"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "spring_app"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_SERVICE_PASSWORD
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_HOST
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_DATABASE
            - name: MONGO_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_APP_NAME
            - name: MONGODB_URI
              value: "mongodb+srv://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST)/$(MONGO_DATABASE)?appName=$(MONGO_APP_NAME)"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: auction-provider-procar
  namespace: procar
spec:
  type: ClusterIP
  selector:
    app: auction-provider-procar
  ports:
    - port: 8083
      targetPort: 8083
