apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-runner

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/attach", "pods/exec", "pods/log", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |
    concurrent = 4
    check_interval = 3

    [[runners]]
      name = "procar-k3s-runner"
      url = "https://gitlab.kintovt.by"
      token = "glrt-YQiKlOk0U1ssqY8-BLLEMm86MQpwOjIKdDozCnU6Nw8.01.171u964cv"
      executor = "kubernetes"

      [runners.kubernetes]
        namespace = "gitlab-runner"
        service_account = "gitlab-runner"
        pull_policy = "if-not-present"
        privileged = true


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      serviceAccountName: gitlab-runner
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:latest
          volumeMounts:
            - name: config
              mountPath: /etc/gitlab-runner
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: gitlab-runner-config
