spring:
  data:
    redis:
      url: "redis://:${REDIS_PASSWORD}@redis:6379"
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

management:
  health:
    redis:
      enabled: false
